---
- name: check zoneinfo
  stat: path=/usr/share/zoneinfo/{{ zonename | default(default_zonename) }} get_checksum=true checksum_algorithm=md5
  register: target_zoneinfo
  tags: [timezone]

- name: skip if zoneinfo is not found.
  fail: msg="{{ zonename | default(default_zonename)}} is not found"
  when: target_zoneinfo.stat.exists != true
  tags: [timezone]

- name: check localtime
  stat: path=/etc/localtime follow=yes get_checksum=true checksum_algorithm=md5
  register: target_localtime
  tags: [timezone]

- name: symlink /etc/localtime
  file:
    src:   /usr/share/zoneinfo/{{ zonename | default(default_zonename) }}
    dest:  /etc/localtime
    state: link
    force: yes
  when:         (target_zoneinfo.stat.checksum is defined) and (target_localtime.stat.checksum is defined) and (target_zoneinfo.stat.checksum != target_localtime.stat.checksum)
  changed_when: (target_zoneinfo.stat.checksum != target_localtime.stat.checksum)
  tags: [timezone]

- name: /etc/sysconfig/clock
  lineinfile:
    dest=/etc/sysconfig/clock
    regexp="^ZONE"
    line='ZONE="{{ zonename | default(default_zonename) }}"'
  register:     is_sysconfig_clock
  when: ( ansible_distribution_major_version != "7" )
  changed_when: is_sysconfig_clock.changed is defined and is_sysconfig_clock.changed
  tags: [timezone]

