FROM centos:6

# Install Ansible
RUN yum -y update \
 && yum clean all \
 && yum -y install epel-release \
 && yum -y install git sudo ansible tzdata \
 && yum clean all

# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Install Ansible inventory file
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

CMD ["/usr/sbin/init"]
